AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - tmp/**/*

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 規定の囲み文字をダブルクォーテーションに変更
StringLiterals:
  EnforcedStyle: double_quotes

# 規定の囲み文字をダブルクォーテーションに変更
StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# 「and」「or」の使用を許可
AndOr:
  Enabled: false

# 改行コードを「CRLF」を許可
EndOfLine:
  EnforcedStyle: crlf

# ネストが深すぎる
BlockNesting:
  Max: 5

# クラスの行数が多すぎる
ClassLength:
  Enabled: false

# 循環的複雑度が高すぎる(ifやforなどを1メソッド内で使いすぎている)
CyclomaticComplexity:
  Enabled: false

# 例外を抑制している
HandleExceptions:
  Enabled: false

# 行が長すぎる
LineLength:
  Enabled: false

# メソッドの行数が多すぎる
MethodLength:
  Enabled: false

# 引数の数が多すぎる
ParameterLists:
  Max: 12

# FrozenStringLiteralsの無効化
FrozenStringLiteralComment:
  Enabled: false
